name: Deploy Lambda Function

on:
  push:
    branches: [ main ]
    paths:
      - 'Lambda-FeecardUpload/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Lambda code
        run: |
          cd Lambda-FeecardUpload
          zip -r ../lambda.zip .

      - name: Deploy to AWS Lambda using ARN
        uses: aws-actions/aws-cli@v1.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          args: lambda update-function-code \
            --function-name arn:aws:lambda:ap-southeast-2:357598733564:function:FeecardUpload \
            --zip-file fileb://lambda.zip
